---
- name: Deploy aplikasi web ke server
  hosts: web_servers
  become: yes
  gather_facts: yes

  vars:
    app_name: lab-webapp
    app_version: "1.0.0"
    app_port: 8080

  roles:
    - role: webapps
      tags: webapps

- name: Deploy database
  hosts: database_servers
  become: yes
  gather_facts: yes

  roles:
    - role: database
      tags: database